<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Authors>Allan Ritchie</Authors>
    <Product>Shiny.Net.HttpServer</Product>
  </PropertyGroup>

</Project>
