name: Feature Request
description: You have an idea for an enhancement within Shiny HTTP Server
title: "[Feature Request]: "
labels: [feature request, unverified]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the feature and, where relevant, which package(s) it should apply to.
  - type: textarea
    attributes:
      label: Summary
      description: Your summary of the feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: API Changes
    validations:
      required: true
  - type: textarea
    attributes:
      label: Intended Use Case
    validations:
      required: true
