using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Shiny.Net.HttpServer.SourceGenerators;

/// <summary>
/// Writes a switchboard's contract as one self-contained C# file: the interface clients call it
/// through, its <c>TClient</c> interface, every data type either mentions, and a JSON context for
/// them — for a client that cannot reference a shared contracts assembly.
/// <para>
/// Types are rendered from symbols rather than copied from source, so the file depends on nothing
/// but the BCL: no usings from the server's files, no server-only namespaces. The whole file sits
/// behind <c>#if SHINY_SWITCHBOARD_CONTRACT_EXPORT</c>, so it compiles to nothing in the server; the
/// package's build target strips that guard when it copies the file out.
/// </para>
/// </summary>
sealed class ContractExporter
{
    public const string Guard = "SHINY_SWITCHBOARD_CONTRACT_EXPORT";

    const string JsonSerializationNamespace = "System.Text.Json.Serialization";
    const string JsonContextType = "System.Text.Json.Serialization.JsonSerializerContext";

    static readonly SymbolDisplayFormat Fq = SymbolDisplayFormat.FullyQualifiedFormat;

    readonly INamedTypeSymbol board;
    readonly Compilation compilation;
    readonly ImmutableArray<DiagnosticInfo>.Builder diagnostics;
    readonly string ns;

    // Declaration order is output order; the set is what has been claimed.
    readonly List<INamedTypeSymbol> exported = [];
    readonly HashSet<INamedTypeSymbol> exportedSet = new(SymbolEqualityComparer.Default);
    readonly HashSet<string> exportedNames = new(StringComparer.Ordinal);
    readonly HashSet<ITypeSymbol> refused = new(SymbolEqualityComparer.Default);
    readonly List<string> serializable = [];

    ContractExporter(INamedTypeSymbol board, string ns, Compilation compilation, ImmutableArray<DiagnosticInfo>.Builder diagnostics)
    {
        this.board = board;
        this.ns = ns;
        this.compilation = compilation;
        this.diagnostics = diagnostics;
    }

    public static ContractModel? Export(
        INamedTypeSymbol board,
        AttributeData attribute,
        IReadOnlyList<(IMethodSymbol Method, string Name)> methods,
        INamedTypeSymbol? client,
        Compilation compilation,
        ImmutableArray<DiagnosticInfo>.Builder diagnostics
    )
    {
        var ns = Named(attribute, "Namespace")
            ?? (board.ContainingNamespace.IsGlobalNamespace ? "Contracts" : board.ContainingNamespace.ToDisplayString() + ".Contracts");

        var boardInterface = Named(attribute, "BoardInterface") ?? "I" + board.Name;

        var exporter = new ContractExporter(board, ns, compilation, diagnostics);
        return new ContractModel($"{board.Name}.Contract.g.cs", exporter.Render(boardInterface, methods, client));
    }

    static string? Named(AttributeData attribute, string name)
        => attribute.NamedArguments.FirstOrDefault(a => a.Key == name).Value.Value as string;

    string Render(string boardInterface, IReadOnlyList<(IMethodSymbol Method, string Name)> methods, INamedTypeSymbol? client)
    {
        // Interfaces first, because rendering them is what discovers the data types.
        var body = new StringBuilder();

        body.Append($"    /// <summary>Calls on <c>{Xml(this.board.ToDisplayString())}</c>.</summary>\n");
        body.Append($"    public interface {boardInterface}\n    {{\n");
        foreach (var (method, name) in methods)
            body.Append("        ").Append(this.RenderBoardMethod(method, name)).Append('\n');
        body.Append("    }\n");

        if (client is not null)
        {
            body.Append('\n');
            body.Append($"    /// <summary>What <c>{Xml(this.board.ToDisplayString())}</c> calls on its clients.</summary>\n");
            body.Append($"    public interface {client.Name}\n    {{\n");
            foreach (var method in new[] { client }.Concat(client.AllInterfaces).SelectMany(i => i.GetMembers().OfType<IMethodSymbol>()).Where(m => m.IsAbstract && m.MethodKind == MethodKind.Ordinary))
                body.Append("        ").Append(this.RenderClientMethod(method)).Append('\n');
            body.Append("    }\n");
        }

        // Rendering a type can discover more types; loop until nothing new turns up.
        var types = new StringBuilder();
        for (var i = 0; i < this.exported.Count; i++)
            types.Append('\n').Append(this.RenderType(this.exported[i]));

        var code = new StringBuilder();
        code.Append("// <auto-generated/>\n");
        code.Append($"// The contract of {this.board.ToDisplayString()}, exported by the Shiny.Net.HttpServer.Switchboard generator.\n");
        code.Append("// Regenerated on every build of the server; do not edit.\n");
        code.Append($"#if {Guard}\n");
        code.Append("#nullable enable\n");
        code.Append("#pragma warning disable CS8618, CS1591\n\n");
        code.Append($"namespace {this.ns}\n{{\n");
        code.Append(body);
        code.Append(types);
        code.Append('\n').Append(this.RenderJsonContext());
        code.Append("}\n");
        code.Append($"#endif // {Guard}\n");

        return code.ToString();
    }

    // ---- interfaces ----

    string RenderBoardMethod(IMethodSymbol method, string name)
    {
        var parameters = new List<string>();

        foreach (var parameter in method.Parameters)
        {
            if (IsCancellationToken(parameter.Type)
                || parameter.Type.ToDisplayString() == "Shiny.Net.HttpServer.Switchboard.CallerContext"
                || parameter.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "Shiny.Net.HttpServer.FromServicesAttribute"))
                continue;

            this.Serializable(parameter.Type);
            parameters.Add(this.RenderParameter(parameter));
        }

        // Every exported call can be cancelled from the client side, whether or not the server
        // method observes it.
        parameters.Add("global::System.Threading.CancellationToken cancellationToken = default");

        string returns;
        if (method.ReturnsVoid)
        {
            returns = "global::System.Threading.Tasks.Task";
        }
        else if (IsAsyncEnumerable(method.ReturnType, out var item))
        {
            this.Serializable(item!);
            returns = $"global::System.Collections.Generic.IAsyncEnumerable<{this.TypeName(item!)}>";
        }
        else if (Awaited(method.ReturnType, out var awaited))
        {
            if (awaited is null)
            {
                returns = "global::System.Threading.Tasks.Task";
            }
            else
            {
                this.Serializable(awaited);
                returns = $"global::System.Threading.Tasks.Task<{this.TypeName(awaited)}>";
            }
        }
        else
        {
            this.Serializable(method.ReturnType);
            returns = $"global::System.Threading.Tasks.Task<{this.TypeName(method.ReturnType)}>";
        }

        return $"{returns} {ClientProxyBuilder.Escape(name)}({string.Join(", ", parameters)});";
    }

    string RenderClientMethod(IMethodSymbol method)
    {
        foreach (var parameter in method.Parameters.Where(p => !IsCancellationToken(p.Type)))
            this.Serializable(parameter.Type);

        if (method.ReturnType is INamedTypeSymbol { IsGenericType: true } task)
            this.Serializable(task.TypeArguments[0]);

        return $"{this.TypeName(method.ReturnType)} {ClientProxyBuilder.Escape(method.Name)}({string.Join(", ", method.Parameters.Select(this.RenderParameter))});";
    }

    string RenderParameter(IParameterSymbol parameter)
    {
        var rendered = $"{this.TypeName(parameter.Type)} {ClientProxyBuilder.Escape(parameter.Name)}";

        if (!parameter.HasExplicitDefaultValue)
            return rendered;

        var value = parameter.ExplicitDefaultValue;
        if (value is null)
            return rendered + " = default";

        // Cast, so enums, floats and decimals come out as constants of the parameter's own type.
        var literal = SymbolDisplay.FormatPrimitive(value, quoteStrings: true, useHexadecimalNumbers: false);
        return $"{rendered} = ({this.TypeName(parameter.Type)})({literal})";
    }

    // ---- types ----

    /// <summary>Records a type the JSON context has to cover, and pulls in the data types inside it.</summary>
    void Serializable(ITypeSymbol type)
    {
        if (type.SpecialType is SpecialType.System_Void or SpecialType.System_Object)
            return;

        // Collected first, so the name below already refers to the exported copy.
        this.Collect(type);

        var name = this.TypeName(type.WithNullableAnnotation(NullableAnnotation.NotAnnotated));
        if (!this.serializable.Contains(name))
            this.serializable.Add(name);
    }

    /// <summary>Finds the source-declared data types inside <paramref name="type"/> and claims them for export.</summary>
    void Collect(ITypeSymbol type)
    {
        switch (type)
        {
            case IArrayTypeSymbol array:
                this.Collect(array.ElementType);
                return;

            case INamedTypeSymbol named when named.NullableUnderlying() is { } underlying:
                this.Collect(underlying);
                return;

            case INamedTypeSymbol named:
                foreach (var argument in named.TypeArguments)
                    this.Collect(argument);

                if (named.SpecialType != SpecialType.None || this.IsExternal(named) || this.exportedSet.Contains(named) || this.refused.Contains(named))
                    return;

                if (this.Refusal(named) is { } reason)
                {
                    this.refused.Add(named);
                    this.diagnostics.Add(DiagnosticInfo.Create(SwitchboardDiagnostics.ContractTypeNotExported, named, named.ToDisplayString(), this.board.ToDisplayString(), reason));
                    return;
                }

                this.exportedSet.Add(named);
                this.exportedNames.Add(named.Name);
                this.exported.Add(named);

                foreach (var property in DataProperties(named))
                    this.Collect(property.Type);

                return;
        }
    }

    /// <summary>A type the client is expected to have already: the BCL, or another assembly.</summary>
    bool IsExternal(INamedTypeSymbol type)
        => !SymbolEqualityComparer.Default.Equals(type.ContainingAssembly, this.compilation.Assembly);

    string? Refusal(INamedTypeSymbol type)
    {
        if (type.TypeKind is not (TypeKind.Class or TypeKind.Struct or TypeKind.Enum))
            return "only classes, structs, records and enums can be exported";

        if (type.IsGenericType)
            return "generic types cannot be exported";

        if (type.ContainingType is not null)
            return "nested types cannot be exported";

        if (type.IsAbstract)
            return "abstract types cannot be exported";

        if (type.TypeKind == TypeKind.Class
            && type.BaseType is { SpecialType: not SpecialType.System_Object })
            return "types with a base class cannot be exported";

        if (this.exportedNames.Contains(type.Name))
            return $"another exported type is already called '{type.Name}'";

        return null;
    }

    static IEnumerable<IPropertySymbol> DataProperties(INamedTypeSymbol type)
        => type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public
                && !p.IsStatic
                && !p.IsIndexer
                && p.GetMethod is not null
                && !(type.IsRecord && p.Name == "EqualityContract"));

    string RenderType(INamedTypeSymbol type)
    {
        var code = new StringBuilder();

        foreach (var attribute in JsonAttributes(type))
            code.Append("    ").Append(attribute).Append('\n');

        if (type.TypeKind == TypeKind.Enum)
        {
            var underlying = type.EnumUnderlyingType is { SpecialType: not SpecialType.System_Int32 } u ? $" : {u.ToDisplayString()}" : "";
            code.Append($"    public enum {type.Name}{underlying}\n    {{\n");

            foreach (var field in type.GetMembers().OfType<IFieldSymbol>().Where(f => f.HasConstantValue))
            {
                foreach (var attribute in JsonAttributes(field))
                    code.Append("        ").Append(attribute).Append('\n');

                code.Append($"        {ClientProxyBuilder.Escape(field.Name)} = {SymbolDisplay.FormatPrimitive(field.ConstantValue!, quoteStrings: false, useHexadecimalNumbers: false)},\n");
            }

            code.Append("    }\n");
            return code.ToString();
        }

        var keyword = type.IsRecord
            ? type.TypeKind == TypeKind.Struct ? "record struct" : "record"
            : type.TypeKind == TypeKind.Struct ? "struct" : "class";

        var sealedModifier = type.IsSealed && type.TypeKind == TypeKind.Class ? "sealed " : "";

        // A positional record keeps its primary constructor, so client code constructs it the same
        // way server code does.
        var positional = PrimaryConstructor(type);
        var positionalNames = new HashSet<string>(positional?.Parameters.Select(p => p.Name) ?? [], StringComparer.Ordinal);

        code.Append($"    public {sealedModifier}{keyword} {type.Name}");

        if (positional is not null)
        {
            code.Append('(');
            code.Append(string.Join(", ", positional.Parameters.Select(p =>
            {
                var attributes = type.GetMembers(p.Name).OfType<IPropertySymbol>().SelectMany(JsonAttributes).Select(a => a.Replace("[", "[property: "));
                var prefix = string.Concat(attributes.Select(a => a + " "));
                return prefix + this.RenderParameter(p);
            })));
            code.Append(')');
        }

        var body = DataProperties(type).Where(p => !positionalNames.Contains(p.Name)).ToList();
        if (body.Count == 0 && positional is not null)
        {
            code.Append(";\n");
            return code.ToString();
        }

        code.Append("\n    {\n");

        foreach (var property in body)
        {
            foreach (var attribute in JsonAttributes(property))
                code.Append("        ").Append(attribute).Append('\n');

            var accessors = property.SetMethod switch
            {
                null => "{ get; init; }",
                { IsInitOnly: true } => "{ get; init; }",
                _ => "{ get; set; }"
            };

            var required = property.IsRequired ? "required " : "";
            code.Append($"        public {required}{this.TypeName(property.Type)} {ClientProxyBuilder.Escape(property.Name)} {accessors}\n");
        }

        code.Append("    }\n");
        return code.ToString();
    }

    static IMethodSymbol? PrimaryConstructor(INamedTypeSymbol type)
    {
        if (!type.IsRecord)
            return null;

        foreach (var reference in type.DeclaringSyntaxReferences)
        {
            if (reference.GetSyntax() is RecordDeclarationSyntax { ParameterList: { } list })
            {
                return type.InstanceConstructors.FirstOrDefault(c =>
                    c.Parameters.Length == list.Parameters.Count
                    && c.Parameters.Select(p => p.Name).SequenceEqual(list.Parameters.Select(p => p.Identifier.ValueText)));
            }
        }

        return null;
    }

    /// <summary>
    /// The <c>System.Text.Json.Serialization</c> attributes on a type or member — a renamed property
    /// or a string-valued enum changes the wire format, so the client's copy has to carry them too.
    /// </summary>
    static IEnumerable<string> JsonAttributes(ISymbol symbol)
    {
        foreach (var attribute in symbol.GetAttributes())
        {
            if (attribute.AttributeClass is not { } attributeClass
                || attributeClass.ContainingNamespace.ToDisplayString() != JsonSerializationNamespace)
                continue;

            var arguments = attribute.ConstructorArguments.Select(a => a.ToCSharpString())
                .Concat(attribute.NamedArguments.Select(a => $"{a.Key} = {a.Value.ToCSharpString()}"));

            yield return $"[{attributeClass.ToDisplayString(Fq)}({string.Join(", ", arguments)})]";
        }
    }

    /// <summary>
    /// The JSON context. Its options come from whichever context in the server already covers these
    /// types, so property casing and the like match on both sides of the wire.
    /// </summary>
    string RenderJsonContext()
    {
        var code = new StringBuilder();

        if (this.FindServerContextOptions() is { } options)
            code.Append("    ").Append(options).Append('\n');

        foreach (var type in this.serializable)
            code.Append($"    [global::System.Text.Json.Serialization.JsonSerializable(typeof({type}))]\n");

        code.Append($"    public partial class {this.board.Name}ContractJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext;\n");
        return code.ToString();
    }

    string? FindServerContextOptions()
    {
        foreach (var type in AllTypes(this.compilation.Assembly.GlobalNamespace))
        {
            if (!DerivesFrom(type, JsonContextType))
                continue;

            var covers = type.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString() == "System.Text.Json.Serialization.JsonSerializableAttribute"
                && a.ConstructorArguments.FirstOrDefault().Value is INamedTypeSymbol covered
                && this.exportedSet.Contains(covered));

            if (!covers)
                continue;

            var options = type.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "System.Text.Json.Serialization.JsonSourceGenerationOptionsAttribute");
            if (options is null)
                return null;

            var arguments = options.ConstructorArguments.Select(a => a.ToCSharpString())
                .Concat(options.NamedArguments.Select(a => $"{a.Key} = {a.Value.ToCSharpString()}"));

            return $"[global::System.Text.Json.Serialization.JsonSourceGenerationOptions({string.Join(", ", arguments)})]";
        }

        return null;
    }

    static IEnumerable<INamedTypeSymbol> AllTypes(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers())
            yield return type;

        foreach (var child in ns.GetNamespaceMembers())
        {
            foreach (var type in AllTypes(child))
                yield return type;
        }
    }

    static bool DerivesFrom(INamedTypeSymbol type, string baseName)
    {
        for (var current = type.BaseType; current is not null; current = current.BaseType)
        {
            if (current.ToDisplayString() == baseName)
                return true;
        }

        return false;
    }

    /// <summary>
    /// Renders a type reference for the exported file: exported types by their new name, everything
    /// else fully qualified, nullability kept.
    /// </summary>
    string TypeName(ITypeSymbol type)
    {
        var nullable = type.IsReferenceType && type.NullableAnnotation == NullableAnnotation.Annotated ? "?" : "";

        switch (type)
        {
            case IArrayTypeSymbol array:
                return $"{this.TypeName(array.ElementType)}[{new string(',', array.Rank - 1)}]{nullable}";

            case INamedTypeSymbol named when named.NullableUnderlying() is { } underlying:
                return this.TypeName(underlying) + "?";

            case INamedTypeSymbol named when this.exportedSet.Contains(named):
                return $"global::{this.ns}.{named.Name}{nullable}";

            case INamedTypeSymbol { SpecialType: not SpecialType.None } special:
                return special.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat).TrimEnd('?') + nullable;

            case INamedTypeSymbol { IsGenericType: true } generic:
                var definition = generic.ConstructedFrom.ToDisplayString(Fq);
                var bare = definition.Substring(0, definition.IndexOf('<'));
                return $"{bare}<{string.Join(", ", generic.TypeArguments.Select(this.TypeName))}>{nullable}";

            default:
                return type.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString(Fq) + nullable;
        }
    }

    static bool IsCancellationToken(ITypeSymbol type) => type.ToDisplayString() == "System.Threading.CancellationToken";

    static bool IsAsyncEnumerable(ITypeSymbol type, out ITypeSymbol? item)
    {
        if (type is INamedTypeSymbol { IsGenericType: true } named
            && named.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.IAsyncEnumerable<T>")
        {
            item = named.TypeArguments[0];
            return true;
        }

        item = null;
        return false;
    }

    static bool Awaited(ITypeSymbol type, out ITypeSymbol? awaited)
    {
        awaited = null;
        if (type is not INamedTypeSymbol named)
            return false;

        switch (named.ConstructedFrom.ToDisplayString())
        {
            case "System.Threading.Tasks.Task":
            case "System.Threading.Tasks.ValueTask":
                return true;

            case "System.Threading.Tasks.Task<TResult>":
            case "System.Threading.Tasks.ValueTask<TResult>":
                awaited = named.TypeArguments[0];
                return true;

            default:
                return false;
        }
    }

    static string Xml(string value) => value.Replace("<", "{").Replace(">", "}");
}

static class NullableExtensions
{
    public static ITypeSymbol? NullableUnderlying(this ITypeSymbol type)
        => type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } named
            ? named.TypeArguments[0]
            : null;
}

sealed record ContractModel(string HintName, string Source);
