// <auto-generated/>
// The contract of Sample.Switchboard.ChatBoard, exported by the Shiny.Net.HttpServer.Switchboard generator.
// Regenerated on every build of the server; do not edit.

#nullable enable
#pragma warning disable CS8618, CS1591

namespace Sample.Switchboard.Contracts
{
    /// <summary>Calls on <c>Sample.Switchboard.ChatBoard</c>.</summary>
    public interface IChatBoard
    {
        global::System.Threading.Tasks.Task JoinRoom(string room, global::System.Threading.CancellationToken cancellationToken = default);
        global::System.Threading.Tasks.Task LeaveRoom(string room, global::System.Threading.CancellationToken cancellationToken = default);
        global::System.Threading.Tasks.Task SendMessage(string room, string text, global::System.Threading.CancellationToken cancellationToken = default);
        global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<global::Sample.Switchboard.Contracts.RoomInfo>> ListRooms(global::System.Threading.CancellationToken cancellationToken = default);
        global::System.Collections.Generic.IAsyncEnumerable<global::Sample.Switchboard.Contracts.ChatMessage> History(string room, int take = (int)(20), global::System.Threading.CancellationToken cancellationToken = default);
        global::System.Threading.Tasks.Task DeleteRoom(string room, global::System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>What <c>Sample.Switchboard.ChatBoard</c> calls on its clients.</summary>
    public interface IChatClient
    {
        global::System.Threading.Tasks.Task MessageReceived(global::Sample.Switchboard.Contracts.ChatMessage message);
        global::System.Threading.Tasks.Task UserJoined(string room, string user);
        global::System.Threading.Tasks.Task UserLeft(string room, string user);
        global::System.Threading.Tasks.Task Notice(string text);
        global::System.Threading.Tasks.Task<bool> ConfirmDelete(string room);
    }

    public sealed record RoomInfo(string Name, int Members);

    public sealed record ChatMessage(string Room, string User, string Text, global::System.DateTimeOffset At);

    [global::System.Text.Json.Serialization.JsonSerializable(typeof(string))]
    [global::System.Text.Json.Serialization.JsonSerializable(typeof(global::System.Collections.Generic.IReadOnlyList<global::Sample.Switchboard.Contracts.RoomInfo>))]
    [global::System.Text.Json.Serialization.JsonSerializable(typeof(int))]
    [global::System.Text.Json.Serialization.JsonSerializable(typeof(global::Sample.Switchboard.Contracts.ChatMessage))]
    [global::System.Text.Json.Serialization.JsonSerializable(typeof(bool))]
    public partial class ChatBoardContractJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext;
}
